### ISSUE TITLE
ToolProvider.getSystemJavaCompiler() returns null

### ISSUE THREAD

**Issue by rustem-s** [picadoh/imc#3]
Hi @picadoh 

I run the application, I get the error NullPointerException.

JavaCompiler getSystemJavaCompiler () {
    return ToolProvider.getSystemJavaCompiler();
}

ToolProvider.getSystemJavaCompiler() returns null.

**Comment by picadoh** [comment]
Is the JAVA_HOME set to a JDK folder? tools.jar is required to run IMC and this is only part of JDK.
